name: bdf-pz
networks:
  beaker:
    name: bdf-pz_beaker

services:
  jupyter:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      - DEBUG=1
      - JUPYTER_SERVER=http://jupyter:8888
      - JUPYTER_TOKEN=89f73481102c46c0bc13b2998f9a4fce
      - ENABLE_USER_PROMPT=true
      - ENABLE_CHECKPOINTS=true
      - PYTHONPATH=/jupyter
    working_dir: /jupyter
    volumes:
      - ./.beaker.conf:/jupyter/.beaker.conf
      - ./testdata/:/jupyter/testdata/
      - ./src/bdf_pz:/jupyter/src/bdf_pz
    networks:
      - beaker

