services:
  ui:
    image: node:20
    user: "node"
    volumes:
      - ./:/ui
    working_dir: "/ui"
    ports:
      - "8080:8080"
    command: "sh -c 'npm install && npm run serve'"
    networks:
      - beaker